project_name: lorawan-stack-migrate

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: ttn-lw-migrate
    main: ./cmd/ttn-lw-migrate
    binary: ttn-lw-migrate
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack-migrate/pkg/version.BuildDate={{ .Date }}
    - -X go.thethings.network/lorawan-stack-migrate/pkg/version.GitCommit={{ .ShortCommit }}
    - -X go.thethings.network/lorawan-stack-migrate/pkg/version.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: ttn-lw-migrate
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - ttn-lw-migrate
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: ttn-lw-migrate
    builds:
      - ttn-lw-migrate
    vendor: The Things Network
    homepage: https://www.thethingsnetwork.org
    maintainer: The Things Network Foundation <stack@thethingsnetwork.org>
    description: Migrate from other LoRaWAN network servers to The Things Stack
    license: Apache 2.0
    formats:
      - deb
      - rpm
    recommends:
      - lorawan-stack

snapcrafts:
  - id: ttn-lw-migrate
    builds:
      - ttn-lw-migrate
    name: ttn-lw-migrate
    summary: Migrate from other LoRaWAN network servers to The Things Stack
    description: Migrate from other LoRaWAN network servers to The Things Stack
    grade: stable
    confinement: strict
    publish: true
    apps:
      ttn-lw-migrate:
        plugs: [ home, network ]
        command: ttn-lw-migrate

brews:
  - name: ttn-lw-migrate
    ids:
      - ttn-lw-migrate
    tap:
      owner: TheThingsNetwork
      name: homebrew-lorawan-stack
    commit_author:
      name: ttn-ci
      email: stack@thethingsnetwork.org
    homepage: https://www.thethingsnetwork.org
    description: Migrate from other LoRaWAN network servers to The Things Stack
    skip_upload: auto
    install: |
      bin.install "ttn-lw-migrate"
